name: backend
description: A web server built using the shelf package.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  socket_io:
    git: https://github.com/stasgora/socket.io-dart.git

dev_dependencies:
  effective_dart: ^1.3.2
