name: backend
description: A web server built using the shelf package.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  socket_io: ^1.0.0

dev_dependencies:
  effective_dart: ^1.3.2
