name: backend
description: End Space game backend server
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  socket_io: ^1.0.0

  equatable: ^2.0.3

dev_dependencies:
  effective_dart: ^1.3.2
